name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.platform }} on ${{ matrix.os }}
    runs-on: macos-latest
    env:
      scheme: APUserAgentGenerator
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iOS Simulator
            device: iPhone 16 Pro
            os: "18.5"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run Test on ${{ matrix.platform }} (iOS ${{ matrix.os }})
        run: |
          xcodebuild test \
            -scheme $scheme \
            -destination 'platform=${{ matrix.platform }},name=${{ matrix.device }},OS=${{ matrix.os }}'
