name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.device }} on ${{ matrix.os }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iOS Simulator
            device: iPhone 16 Pro
            os: 18.2
          - platform: tvOS Simulator
            device: Apple TV
            os: 18.2
          - platform: watchOS Simulator
            device: Apple Watch Series 10
            os: 11.2
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set project name from repo slug
        run: echo "scheme=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Run test on ${{ matrix.device }} (iOS ${{ matrix.os }})
        run: |
          set -o pipefail && \
             xcodebuild \
             -scheme ${{ env.scheme }} \
             -destination 'platform=${{ matrix.platform }},name=${{ matrix.device }},OS=${{ matrix.os }}' \
             -enableCodeCoverage YES \
             -derivedDataPath ./DerivedData \
             -resultBundlePath ./TestResults.xcresult test
      
      # Install xcresultparser
      - name: Install xcresultparser
        run: brew install xcresultparser
        
      # Generate lcov report using Slather
      - name: Generate Coverage Report
        run: |
          slather coverage \
            --scheme ${{ env.scheme }} \
            --output-directory ./coverage \
            --cobertura-xml \
            --build-directory ./DerivedData \
            ./${{ env.scheme }}.xcodeproj

      # Convert .xcresult to JUnit XML for test results
      - name: Convert Test Results to JUnit
        run: |
          xcresultparser \
            --output-format junit \
            ./TestResults.xcresult > ./test-results.xml
            
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          files: ./coverage/cobertura.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          files: ./test-results.xml
